@extends('partials.layouts.base')

@section('content')
    <main class="light">
        <section class="erd-paris" id="erd-paris">
            <div class="container-full">
                <div class="erd-paris__row" style="align-items:normal">
                    <div class="erd-paris__left">
                        <div class="erd-paris__headlines">
                            <h1 class="erd-paris__title">@if(Session::get('lang') == 'en') LEGAL @else ЮРИДИЧНА ІНФОРМАЦІЯ @endif</h1>
                        </div>
                    </div>
                    <div class="erd-paris__right" >
                        @if(Session::get('lang') == 'en')
                            PRIVACY POLICY<br>
                            WELCOME TO OUR WEBSITE WWW.LOSTKIDSCLUB2000.COM (THE “SITE”). PLEASE READ OUR PRIVACY POLICY CAREFULLY.<br><br>

                            THIS PRIVACY POLICY APPLIES WHEN YOU VISIT OR SURF THE SITE WITHOUT PURCHASING ANY PRODUCT, WHEN YOU REGISTER ON THE SITE AND WHEN YOU USE OUR SERVICES FOR PURCHASING PRODUCTS. BY USING THIS SITE, YOU ACCEPT THE PRACTICES DESCRIBED IN THIS PRIVACY POLICY. IF YOU DO NOT WANT TO ACCEPT THE PRACTICES DESCRIBED IN THIS PRIVACY POLICY, PLEASE DO NOT USE THE SITE.<br><br>

                            SINCE PERSONAL DATA (“PERSONAL DATA”) OF USERS AND CUSTOMERS (COLLECTIVELY "USERS") OF THIS SITE MAY BE PROCESSED IN THE EUROPEAN UNION, NOTABLY IN ITALY, ANY PROCESSING OF PERSONAL DATA WILL BE CONDUCTED IN COMPLIANCE WITH APPLICABLE EUROPEAN LAWS.<br><br>

                            YOUR PERSONAL DATA ARE COLLECTED AND PROCESSED BY LOSTKIDSCLUB2000 AS WELL AS BY THEIR SERVICE PROVIDERS LOCATED WITHIN AND OUTSIDE OF THE UNITED STATES (COLLECTIVELY "US", "WE", "OUR"). LOSTKIDSCLUB2000<br><br>

                            YOUR PERSONAL DATA WILL BE PROCESSED TO PROVIDE THE SERVICES YOU SUBSCRIBED TO OR RESERVED FOR REGISTERED USERS, TO FACILITATE YOUR NAVIGATION OF AND SHOPPING FROM THE WEBSITE AND TO KEEP YOU INFORMED OF LOSTKIDSCLUB2000 NEWS AND OFFERS.<br><br>

                            LOSTKIDSCLUB2000 IS THE CONTROLLER OF PERSONAL DATA COLLECTED AND PROCESSED FOR PURPOSE OF RENDERING THE E-COMMERCE SERVICES AND THE SALE OF PRODUCTS (HEREIN THE "COMMERCIAL PURPOSES") THROUGH THE SITE.<br><br>

                            LOSTKIDSCLUB2000 IS THE CONTROLLER OF PERSONAL DATA OF USERS AND CUSTOMERS OF THE SITE THROUGHOUT THE WORLD, WHICH IS COLLECTED FOR CONDUCTING, CONCLUDING AND PERFORMING TRANSACTIONS FOR PURCHASING PRODUCTS ON THE AFOREMENTIONED SITE. LOSTKIDSCLUB2000 ENSURES THAT PERSONAL DATA ARE PROCESSED IN A CORRECT AND LAWFUL MANNER AND IN ACCORDANCE WITH GOOD PRACTICE. ANY SUCH PROCESSING OF PERSONAL DATA WILL BE CONDUCTED IN COMPLIANCE WITH APPLICABLE US LAW.<br><br>

                            LOSTKIDSCLUB2000 C IS THE SOLE DATA CONTROLLER OF THE PERSONAL DATA PROCESSED FOR MARKETING PURPOSES, NOTABLY TO SEND TO USERS, ALSO THROUGH NEWSLETTER, INFORMATION AND UPDATES ON ITS PRODUCTS, OFFERS, EXCLUSIVE SALES, PROMOTIONAL CAMPAIGNS AND ON EVENTS AND SIMILAR INITIATIVES ORGANIZED BY LOSTKIDSCLUB2000 (HEREIN THE "MARKETING PURPOSES”).<br><br>

                            1. OUR POLICY EVERYONE HAS THE RIGHT TO PROTECTION OF HIS/HER PERSONAL DATA. WE RESPECT USERS' RIGHT TO BE INFORMED REGARDING THE COLLECTION OF AND OTHER OPERATIONS INVOLVING THEIR PERSONAL DATA. IN USING DATA THAT MAY DIRECTLY OR INDIRECTLY IDENTIFY YOU PERSONALLY, WE WILL APPLY A PRINCIPLE OF STRICT NECESSITY. FOR THIS REASON, WE HAVE DESIGNED THE SITE IN SUCH A WAY THAT THE USE OF YOUR PERSONAL DATA WILL BE KEPT TO A MINIMUM AND WILL NOT EXCEED THE PURPOSES FOR WHICH YOUR PERSONAL DATA WAS COLLECTED AND/OR PROCESSED; WE DO NOT PROCESS YOUR PERSONAL DATA WHEN WE CAN PROVIDE YOU WITH SERVICES THROUGH THE USE OF ANONYMOUS OR TRAFFIC DATA (SUCH AS MARKETING RESEARCH MADE FOR IMPROVING OUR SERVICES, BROWSING DATA PROCESSED TO PROVIDE YOU WITH CUSTOMIZED CONTENTS OR OFFERS ADAPTED TO YOUR PREFERRED LANGUAGE, YOUR LOCATION, ETC) OR BY OTHER MEANS WHICH ALLOW US TO IDENTIFY YOU, APART FROM WHEN IT IS STRICTLY NECESSARY OR UPON REQUEST BY COMPETENT PUBLIC AUTHORITIES OR THE POLICE (FOR EXAMPLE, IN CASE OF TRAFFIC DATA OR YOUR IP ADDRESS).<br><br>

                            THIS PRIVACY POLICY PROVIDES YOU WITH ALL INFORMATION NEEDED TO UNDERSTAND HOW WE COLLECT DATA WHICH MAY IDENTIFY THE SITE’S USERS. FOR FURTHER INFORMATION ON OUR PRIVACY POLICY, PLEASE CONTACT US THROUGH OUR CUSTOMER CARE AND SELECT ‘PRIVACY’ AS THE SUBJECT IN THE APPROPRIATE FORM, OR AT ENFANTS RICHES DEPRIMES, LLC AT ITS RESPECTIVE REGISTERED OFFICE INDICATED ABOVE.<br><br>

                            2. WHO COLLECTS AND PROCESSES YOUR PERSONAL DATA, HOW AND FOR WHICH PURPOSES? LOSTKIDSCLUB2000 MAY BE THE CONTROLLER OF YOUR PERSONAL DATA AS IT DETERMINES THE COMMERCIAL PURPOSES AND MEANS OF PROCESSING PERSONAL DATA. FOR THE COMMERCIAL PURPOSES ONLY, LOSTKIDSCLUB2000, HAS APPOINTED CERTAIN ENTITIES THAT WILL ALSO PROCESS PERSONAL DATA RELATING TO THE SITE’S USERS (HEREIN THE "PROCESSORS").<br><br>

                            THE ABOVE MENTIONED SERVICE PROVIDERS AND PROCESSORS HAVE BEEN CHOSEN BECAUSE OF THEIR EXPERIENCE IN PROCESSING PERSONAL DATA AND THEY PROVIDE SUFFICIENT GUARANTEES REGARDING COMPLIANCE WITH DATA PROTECTION LAWS (INCLUDING THE TECHNICAL SECURITY MEASURES GOVERNING THE PROCESSING TO BE CARRIED OUT). IN PROCESSING THE PERSONAL DATA FOR COMMERCIAL PURPOSES, THE PROCESSORS SHALL ACT ONLY UNDER THE INSTRUCTIONS FROM ENFANTS RICHES DEPRIMES, LLC. WE REGULARLY CHECK THAT OUR PROCESSORS COMPLY WITH OUR INSTRUCTIONS AND THAT THEY CONTINUE TO PROVIDE SUFFICIENT GUARANTEES REGARDING THEIR FULL COMPLIANCE WITH THE PROVISIONS ON PERSONAL DATA PROCESSING.<br><br>

                            SOME OF THE PROCESSORS OF YOUR PERSONAL DATA APPOINTED BY ENFANTS RICHES DEPRIMES, LLC FOR COMMERCIAL PURPOSES DIRECTLY ARE:<br><br>

                            FEDERAL EXPRESS, INC. FOR PURPOSES RELATED TO SHIPPING, DELIVERING AND RETURNING PRODUCTS PURCHASED ON WEBSITE WWW.LOSTKIDSCLUB2000.COM;<br><br>

                            GODADDY, INC. FOR PURPOSES RELATED TO THE HOUSING OF LOSTKIDSCLUB2000 DOMAIN SERVERS;<br><br>

                            SHOPIFY, INC. FOR PURPOSES PROVIDING THE ONLINE STORE’S SOFTWARE AND RETAIL POINT-OF-SALE SYSTEMS.<br><br>

                            RISKIFIED, INC. FOR PURPOSES OF MONITORING AND PREVENTING E-COMMERCE FRAUD.<br><br>

                            AUTHORIZE.NET, INC. FOR PURPOSES OF ACTING AS OUR ONLINE PAYMENT GATEWAY.<br><br>

                            SIGNATURE CARD SERVICES, INC. FOR PURPOSES OF ACTING AS OUR PAYMENT PROCESSOR.<br><br>

                            FOR THE COMMERCIAL PURPOSES, WE COLLECT YOUR PERSONAL DATA (SUCH AS PERSONAL DETAILS, EMAIL, ADDRESS, CREDIT CARD NUMBERS, BANK CODE, TAX CODE AND TELEPHONE NUMBER, ETC.) ON YOUR ORDER FORM ONLY FOR THE PURPOSE OF SELLING THE PRODUCTS ORDERED BY YOU. YOUR PERSONAL DATA IS MOSTLY PROCESSED BY ELECTRONIC MEANS AND, IN SOME CIRCUMSTANCES, BY PAPER-BASED MEANS, SUCH AS WHEN THE PROCESSING OF YOUR PERSONAL DATA IS REQUIRED FOR PREVENTING FRAUD ON THE SITE. YOUR PERSONAL DATA SHALL BE STORED IN A WAY WHICH ALLOWS US TO IDENTIFY YOU FOR THE PERIOD NECESSARY FOR THE PURPOSES WHICH THE DATA WAS COLLECTED FOR AND SUBSEQUENTLY PROCESSED AND, IN ANY CASE, IN ACCORDANCE WITH APPLICABLE LAWS. PLEASE REPORT ANY MODIFICATION OF YOUR PERSONAL DATA TO OUR CUSTOMER CARE AND SELECT ‘PRIVACY’ AS THE SUBJECT IN THE APPROPRIATE FORM OR THROUGH YOU PERSONAL ACCOUNT ON THE SITE IN ORDER TO ENSURE THAT YOUR PERSONAL DATA IS ALWAYS ACCURATE AND UP-TO-DATE, RELEVANT AND COMPLETE. YOUR PERSONAL DATA SHALL NOT BE DISCLOSED TO THIRD PARTIES OTHER THAN US FOR PURPOSES WHICH ARE NOT PERMITTED BY LAW OR WITHOUT YOUR CONSENT.<br><br>

                            ASIDE FROM THE PROCESSORS APPOINTED FOR PERSONAL DATA PROCESSING, YOUR PERSONAL DATA WILL BE MADE AVAILABLE ALSO TO THIRD PARTIES, AUTONOMOUS CONTROLLERS, FOR PURPOSES RELATED TO SUPPLYING SERVICES REQUESTED BY USERS (FOR EXAMPLE, FOR PURCHASE TRANSACTIONS) OR FOR PURPOSES OF THIRD PARTIES. FOR MORE INFORMATION ON THE MATTER, SEE SECTION 4 (TO WHOM YOUR PERSONAL DATA WILL BE DISCLOSED). PLEASE CONTACT OUR CUSTOMER CARE AND SELECT ‘PRIVACY’ AS THE SUBJECT IN THE APPROPRIATE FORM IF YOU WOULD LIKE TO RECEIVE A FULL LIST OF OUR DATA PROCESSORS INVOLVED IN PROCESSING YOUR PERSONAL DATA.<br><br>

                            FOR THE MARKETING PURPOSES, WE MAY PROCESS YOUR PERSONAL DATA AS WELL AS BROWSING DATA ("TRAFFIC DATA") RESULTING FROM THE USE OF THE SITE AND OF OUR SERVICES BY ANY USER, IN ORDER TO PROVIDE USERS WITH CUSTOMIZED CONTENTS AND OFFERS ON OUR SERVICES OR TO DELIVER ANY NEWSLETTER THEY SUBSCRIBED TO, SUBJECT TO THEIR DISCRETIONARY RIGHT TO WITHDRAW THEIR SUBSCRIPTION TO SUCH NEWSLETTER OR TO OPPOSE OR OBJECT TO THE RECEIVING OF ANY ADVERTISING OR MARKETING CONTENT WHICH WE THINK IS OF INTEREST TO A SPECIFIC USER. FOR MARKETING PURPOSES, PERSONAL DATA AND TRAFFIC DATA IS MOSTLY PROCESSED BY ELECTRONIC MEANS AND SHALL BE STORED IN ANY CASE, IN ACCORDANCE WITH APPLICABLE LAWS AND AVAILABLE TO OUR PROCESSORS.<br><br>

                            MOREOVER, YOUR PERSONAL DATA MAY BE DISCLOSED TO THE POLICE OR TO JUDICIAL AUTHORITIES, ACCORDING TO APPLICABLE LAWS AND UPON A FORMAL REQUEST BY SUCH ENTITIES, FOR EXAMPLE IN THE EVENT WE NEED TO PREVENT FRAUD ON THE SITE (ANTI-FRAUD SERVICES).<br><br>

                            DATA PROCESSORS WILL ALSO HAVE ACCESS TO YOUR PERSONAL DATA AS STATED IN SECTION 2 FOR THE SPECIFIC PURPOSES STATED THEREIN. IN ALL THE ABOVE CIRCUMSTANCES, YOUR CONSENT FOR DATA PROCESSING IS NOT REQUIRED AS PERSONAL DATA PROCESSING WOULD BE NECESSARY FOR THE PERFORMANCE OF COMMERCIAL PURPOSES.<br><br>

                            THE REASONS FOR COLLECTING PERSONAL DATA WILL BE EXPRESSLY LISTED IN THE INFORMATION OF PRIVACY STATEMENT THAT WE WILL PRESENT FROM TIME TO TIME ON THE PAGE ASKING THE USER TO PROVIDE HIS OR HER PERSONAL DATA, BE IT FOR COMMERCIAL PURPOSES OR FOR MARKETING PURPOSES. WE MAY HAVE ACCESS TO THIRD PARTIES' PERSONAL DATA WHICH WAS DIRECTLY DISCLOSED BY ITS USERS, FOR EXAMPLE WHEN A USER BOUGHT A PRODUCT TO BE SENT TO A FRIEND, WHEN THE USER PAYING FOR THE PRODUCT IS DIFFERENT FROM THE RECIPIENT OF THE PRODUCT, OR WHEN A USER WISHES TO RECOMMEND TO A FRIEND A SERVICE OF THE SITE OR THE SALE OF A PARTICULAR PRODUCT. IN ALL OF THE ABOVE CASES, PLEASE MAKE SURE YOU RECEIVE THE CONSENT OF SUCH INDIVIDUALS BEFORE DISCLOSING THEIR PERSONAL DATA TO US AND MAKE SURE YOU INFORM THEM ABOUT THIS PRIVACY POLICY; YOU WILL BE THE ONLY PERSON LIABLE IN CONNECTION WITH THE DISCLOSURE OF INFORMATION AND DATA REGARDING SUCH THIRD PARTIES IF THEY HAVE NOT PROVIDED YOU WITH THEIR PRIOR EXPLICIT CONSENT FOR IT AND FOR ANY IMPROPER AND UNLAWFUL USE OF THAT INFORMATION. IN ANY EVENT, WE SHALL FULFILL ANY OBLIGATION TO INFORM THIRD PARTIES REQUIRED BY LAW AND, WHEN NECESSARY, SHALL REQUEST THEIR EXPLICIT CONSENT UPON REGISTERING IN THEIR ARCHIVES THE PERSONAL DATA OF THE USER INDICATED.<br><br>

                            3. WHAT HAPPENS IF YOU DO NOT DISCLOSE YOUR PERSONAL DATA TO US? GRANTING YOUR PERSONAL DATA TO US (IN PARTICULAR, YOUR PERSONAL DETAILS, YOUR EMAIL, YOUR ADDRESS, YOUR CREDIT/DEBIT CARD NUMBERS AND BANK CODE AND YOUR TELEPHONE NUMBER) IS NECESSARY FOR PROCESSING YOUR ORDER FOR THE PURCHASE OF PRODUCTS ON THE SITE, SUPPLYING OTHER SERVICES PROVIDED ON THE WEBSITE UPON YOUR REQUEST, OR WHEN YOUR PERSONAL DATA IS NEEDED TO FULFILL OBLIGATIONS REQUIRED BY LAW OR REGULATIONS. THE REFUSAL TO PROVIDE US WITH SOME OF YOUR PERSONAL DATA NECESSARY FOR PERFORMING THE ABOVE PURPOSES MAY CONSEQUENTLY PREVENT US FROM PROCESSING YOUR ORDER FOR THE PURCHASE OF PRODUCTS SOLD ON THE SITE OR FULFILLING OBLIGATIONS REQUIRED BY LAW AND OTHER REGULATIONS. THEREFORE, FAILING TO PROVIDE PERSONAL DATA MAY CONSTITUTE, IN SOME CASES, A LEGITIMATE AND JUSTIFIED REASON FOR NOT PROCESSING YOUR ORDER FOR THE PURCHASE OF PRODUCTS SOLD ON THE SITE OR NOT PROVIDING THE SITE’S SERVICES.<br><br>

                            DISCLOSURE OF FURTHER PERSONAL DATA TO US OTHER THAN THAT REQUIRED FOR FULFILLING LEGAL OR CONTRACTUAL OBLIGATIONS AND TO PROPERLY BROWSE OUR SERVICES WITH NECESSARY TRAFFIC DATA IS, ON THE CONTRARY, OPTIONAL AND DOES NOT HAVE ANY EFFECT ON THE USE OF THE SITE AND OF ITS SERVICES OR ON THE PURCHASE OF PRODUCTS ON THE SITE. WE WILL INFORM YOU AT EVERY STEP WHETHER DISCLOSING YOUR PERSONAL DATA TO US IS COMPULSORY OR OPTIONAL BY MARKING WITH AN APPROPRIATE SYMBOL (*) THE INFORMATION THAT IS COMPULSORY OR DATA NEEDED FOR THE PURCHASE OF PRODUCTS ON THE SITE.<br><br>

                            4. TO WHOM YOUR PERSONAL DATA WILL BE DISCLOSED? PERSONAL DATA WILL BE DISCLOSED TO THIRD PARTY COMPANIES THAT PROVIDE, ON BEHALF OF ENFANTS RICHES DEPRIMES, LLC, SPECIFIC SERVICES AS DATA PROCESSORS OR TO OTHER RECIPIENTS OF PERSONAL DATA COLLECTED BY US THAT PROCESS YOUR PERSONAL DATA ONLY FOR THE COMMERCIAL PURPOSES AND, IN ANY CASE, ACCORDING TO APPLICABLE LAWS AND REGULATIONS.<br><br>

                            NOTWITHSTANDING THE FOREGOING, PERSONAL DATA WILL NOT BE DISCLOSED TO ANY OTHER THIRD PARTIES OR DISSEMINATED OR TRANSFERRED WITHOUT INFORMING OUR USERS OF SUCH DISCLOSURE/DISSEMINATION/TRANSFER, AND, IN ANY CASE, IN ACCORDANCE WITH THE APPLICABLE LAWS.<br><br>

                            5. SECURITY MEASURES WE HAVE ADOPTED SECURITY MEASURES TO PROTECT PERSONAL DATA AGAINST ACCIDENTAL OR UNLAWFUL DESTRUCTION, ACCIDENTAL LOSS, ALTERATION, UNAUTHORIZED DISCLOSURE OR ACCESS, AND AGAINST ALL OTHER REASONS FOR DATA PROCESSING THAT DO NOT COMPLY WITH OUR PRIVACY POLICY. FOR THE BEST POSSIBLE PROTECTION OF YOUR PERSONAL DATA OUTSIDE THE LIMITS OF OUR CONTROL AND MANAGEMENT OF THE SAME, IT IS ADVISABLE THAT YOUR COMPUTER BE PROVIDED WITH SOFTWARE DEVICES THAT PROTECT NETWORK DATA TRANSMISSION/RECEIPT (SUCH AS UPDATED ANTIVIRUS SYSTEMS) AND THAT YOUR INTERNET SERVICE PROVIDER TAKE APPROPRIATE MEASURES FOR THE SECURITY OF NETWORK DATA TRANSMISSION (SUCH AS, FOR EXAMPLE, FIREWALLS AND ANTI-SPAM FILTERING).<br><br>

                            6. COOKIES THE SITE USES AUTOMATIC SYSTEMS OF TRAFFIC DATA COLLECTION, SUCH AS COOKIES. A COOKIE IS A FILE STORED ON THE HARD DISK OF THE TERMINAL OF AN INTERNET USER; IT DOES NOT CONTAIN INTELLIGIBLE INFORMATION BUT IT ALLOWS LINKING BETWEEN A TERMINAL AND OTHER INFORMATION ABOUT USER'S EXPERIENCE ON THE SITE AND HIS/HER PREFERENCES EXPRESSED WHILE CHOOSING SERVICES AND PURCHASING PRODUCTS OFFERED BY THE SITE PROVIDED BY THE USERS. FOR COOKIES DISSEMINATED BY OUR SERVERS, NO ONE ELSE MAY GAIN ACCESS TO THE INFORMATION CONTAINED THEREIN. THESE INFORMATION AND DATA ARE GATHERED DIRECTLY AND AUTOMATICALLY BY THE SITE. THE INFORMATION COLLECTED BY COOKIES WILL BE PROCESSED IN ORDER TO OPTIMIZE THE SERVICES OF THE SITE. WE HAVE PROVIDED COOKIES IN CONNECTION TO FUNCTIONS SUCH AS SELECTING THE COUNTRY, THE LANGUAGE, THE LOCATION, BROWSING THE CATALOGUE, PURCHASING PRODUCTS ONLINE AND IN GENERAL IN CONNECTION WITH THE PROVISION OF SERVICES RESERVED TO REGISTERED CUSTOMERS. EACH INTERNET BROWSER ALLOWS THE BLOCKING OR THE DELETION OF COOKIES. YOUR INTERNET BROWSER CONTAINS INSTRUCTIONS ON THESE PROCEDURES. PLEASE ACCESS THE INFORMATION ON YOUR INTERNET BROWSER IF YOU WISH TO DELETE COOKIES.<br><br>

                            THE ACCEPTANCE OF AUTOMATIC DATA COLLECTION PROCEDURES AND THE USE OF COOKIES ARE NECESSARY FOR USING THE SITE AND ITS SERVICES, INCLUDING THE PURCHASE OF PRODUCTS. IF YOU HAVE STARTED THE PROCEDURE OF BLOCKING OR DELETING COOKIES, WE CANNOT ENSURE THAT ALL WEB PAGES OF THE SITE WILL BE DISPLAYED OR THAT CERTAIN SERVICES WILL BE SUPPLIED SUCH AS, FOR EXAMPLE, STORAGE OR DISPLAY ON THE WEB PAGES OF PRODUCTS YOU CHOSE WHEN YOU WERE FINALIZING THE ONLINE PURCHASE PROCESSES.<br><br>

                            7. COMPULSORY PROCESSING WE WISH TO INFORM YOU THAT WE MAY PROCESS YOUR PERSONAL DATA ALSO WITHOUT YOUR CONSENT IN CERTAIN CIRCUMSTANCES PROVIDED BY LAWS.<br><br>

                            8. YOUR RIGHT TO ACCESS PERSONAL DATA AND FURTHER RIGHTS YOU ARE ENTITLED TO OBTAIN, AT ANY TIME, CONFIRMATION FROM US AS TO WHETHER OR NOT DATA RELATING TO YOU IS BEING PROCESSED, WHETHER THE DATA IS NOT YET REGISTERED, AND THE COMMUNICATION IN INTELLIGIBLE FORM OF THE DATA UNDERGOING PROCESSING. MOREOVER, YOU ARE ENTITLED TO RECEIVE FROM US INFORMATION ON THE SOURCE OF YOUR PERSONAL DATA; THE PURPOSES AND WAY OF PROCESSING YOUR PERSONAL DATA; THE LOGIC INVOLVED IN ANY ELECTRONIC DATA PROCESSING; DETAILS OF THE DATA CONTROLLER AND OF THE DATA PROCESSORS; THE NAMES OF THE ENTITIES AND CATEGORIES OF ENTITIES TO WHOM YOUR PERSONAL DATA MAY BE DISCLOSED OR WHO MAY ACCESS YOUR PERSONAL DATA, FOR EXAMPLE, AS A DATA CONTROLLER OR A PARTY SO APPOINTED. YOU CAN EASILY FIND PART OF THE ABOVE INFORMATION IN OUR PRIVACY POLICY. FOR FURTHER INFORMATION, CONTACT OUR CUSTOMER CARE.<br><br>

                            YOU ARE ENTITLED TO OBTAIN AT ANY TIME FROM US:<br><br>

                            A. THE UPDATING, ADJUSTMENT OR, WHEN YOU HAVE AN INTEREST IN SUCH, THE INTEGRATION OF YOUR PERSONAL DATA;<br><br>

                            B. THE DELETION, THE TRANSFORMATION INTO AN ANONYMOUS FORM OR BLOCKING OF YOUR PERSONAL DATA (UNLAWFULLY PROCESSED), INCLUDING DATA WHICH DOES NOT NEED TO BE STORED FOR THE PURPOSES FOR WHICH IT WAS COLLECTED AND SUBSEQUENTLY PROCESSED;<br><br>

                            C. THE CONFIRMATION THAT THE OPERATIONS UNDER LETTERS A) AND B) HAVE BEEN REPORTED (TOGETHER WITH THE CONTENTS OF THE SAME) TO WHOM THE DATA WAS DISCLOSED OR DISSEMINATED, EXCEPT WHEN IT BECOMES IMPOSSIBLE OR IF THE MEANS USED ARE CLEARLY DISPROPORTIONATE TO THE RIGHT'S PROTECTION.<br><br>

                            YOU ARE ENTITLED TO OBJECT, IN WHOLE OR IN PART:<br><br>

                            A. FOR LEGITIMATE REASONS, TO THE PROCESSING OF YOUR PERSONAL DATA, EVEN IF IT IS RELATED TO THE PURPOSES FOR WHICH IT WAS COLLECTED;<br><br>

                            B. TO THE PROCESSING OF YOUR PERSONAL DATA FOR ADVERTISING OR DIRECT MARKETING PURPOSES OR IN ORDER TO CARRY OUT MARKETING RESEARCH OR COMMERCIAL COMMUNICATIONS.<br><br>

                            YOU MAY FREELY EXERCISE YOUR RIGHTS AT ANY TIME, PROVIDED THAT YOU DO SO IN COMPLIANCE WITH APPLICABLE LAWS, BY SENDING YOUR REQUEST TO US THROUGH OUR CUSTOMER CARE AND SELECT ‘PRIVACY’ AS THE SUBJECT IN THE APPROPRIATE FORM OR BY WRITING TO US AT OUR RESPECTIVE ADDRESS MENTIONED IN INTRODUCTION TO THIS PRIVACY POLICY. WE WILL REPLY TO YOU AS NECESSARY.<br><br>

                            9. OPT-IN/OPT OUT EACH TIME YOUR CONSENT IS REQUIRED, ENFANTS RICHES DEPRIMES, LLC WILL INFORM YOU IN ADVANCE AND WILL GIVE YOU THE OPTION TO EITHER PROVIDE OR REFUSE YOUR CONSENT FOR THE USE OF YOUR PERSONAL DATA, INCLUDING YOUR EMAIL, FOR THE ABOVE PURPOSES, BY TICKING THE APPROPRIATE BOXES.<br><br>

                            WE WISH TO INFORM YOU THAT WE MAY PROCESS YOUR PERSONAL DATA ALSO WITHOUT YOUR CONSENT IN CERTAIN CIRCUMSTANCES, SUCH AS WHEN SUCH PROCESSING IS NECESSARY FOR PERFORMING A LEGAL OBLIGATION TO WHICH WE ARE SUBJECT OR WHEN SUCH PROCESSING IS NECESSARY FOR PERFORMING OBLIGATIONS UNDERTAKEN IN CONTRACTS WITH THE USERS.<br><br>

                            TO THE EXTENT OF APPLICABLE LAWS AND SUBJECT TO YOUR RIGHTS, YOUR PERSONAL DATA MAY BE PROCESSED BY US FOR SENDING YOU ADVERTISING OR OFFERS FOR MARKETING PURPOSES ABOUT PRODUCTS AND SERVICES UNLESS YOU OBJECT TO IT AT ANY TIME, EITHER WHEN YOUR PERSONAL DATA HAS BEEN COLLECTED OR AT ANY TIME, NOTABLY WHEN RECEIVING ANY OFFER FROM US.<br><br>

                            IN ANY CASE, WE WISH TO INFORM YOU THAT WE GUARANTEE THAT OUR USERS MAY EXERCISE, AT ANY TIME AND WITHOUT HAVING TO STATE THEIR REASONING, THEIR RIGHT NOT TO RECEIVE FUTURE COMMUNICATIONS CONNECTED TO PARTICULAR SERVICES UPON REQUEST<br><br>

                            10. LINKS TO OTHER WEBSITES WE DO NOT CONTROL OR MONITOR SUCH WEBSITES OR THEIR WEB CONTENT. WE SHALL NOT BE HELD LIABLE FOR THE WEB CONTENT OF SUCH SITES AND FOR THE RULES ADOPTED BY THEM IN TERMS OF YOUR PRIVACY AND THE PROCESSING OF YOUR PERSONAL DATA WHILE YOU ARE VISITING THOSE WEBSITES. PLEASE, PAY ATTENTION WHEN YOU CONNECT TO THESE WEBSITES THROUGH THE LINKS PROVIDED ON OUR WEBSITE AND READ THEIR TERMS AND CONDITIONS OF USE AND THEIR PRIVACY POLICY CAREFULLY. OUR PRIVACY POLICY DOES NOT APPLY TO THIRD PARTY WEBSITES AND WE ARE BY NO MEANS LIABLE FOR THE PRIVACY POLICY ADOPTED BY THOSE WEBSITES. THE SITE PROVIDES LINKS TO OTHER WEBSITES EXCLUSIVELY TO HELP ITS USERS IN THEIR SEARCHES AND NET-SURFING ACTIVITIES AND TO ALLOW LINKS TO OTHER WEBSITES ON THE INTERNET. WHEN WE PROVIDE LINKS TO OTHER WEBSITES, WE DO NOT RECOMMEND THE USE OF THESE WEBSITES AND DO NOT PROVIDE ANY GUARANTEES REGARDING THEIR WEB CONTENT OR THE SERVICES AND PRODUCTS SUPPLIED AND SOLD BY THESE WEBSITES TO INTERNET USERS.<br><br>

                            11. CONTACTS IF YOU WISH TO RECEIVE FURTHER INFORMATION ON HOW WE PROCESS YOUR PERSONAL DATA, PLEASE CONTACT OUR CUSTOMER SERVICE.<br><br>

                            12. GOVERNING LAW TO THE EXTENT THAT WE ARE RESPECTIVELY ESTABLISHED IN THE UNITED STATES, THIS PRIVACY POLICY IS GOVERNED BY UNITED STATES LAW (HEREIN AND TOGETHER, "GOVERNING LAWS"):<br><br>

                            FOR THE PROCESSING OF PERSONAL DATA CARRIED OUT BY ENFANTS RICHES DEPRIMES, LLC AS A DATA CONTROLLER FOR ONLINE SELLING OPERATIONS MANAGEMENT; AND<br><br>

                            FOR THE OTHER PROCESSING OF PERSONAL DATA CARRIED OUT BY ENFANTS RICHES DEPRIMES, LLC, AS A DATA<br><br>

                            CONTROLLER FOR ANY OTHER PROCESSING OPERATIONS.<br><br>

                            13. AMENDMENTS AND UPDATING OF THIS PRIVACY POLICY WE MAY AMEND OR SIMPLY UPDATE ALL OR PART OF THIS PRIVACY POLICY, INCLUDING WHEN AMENDMENTS ARE MADE TO LEGAL PROVISIONS OR REGULATIONS WHICH GOVERN DATA PROTECTION AND PROTECT YOUR RIGHTS. THE AMENDMENTS AND THE UPDATING OF THE PRIVACY POLICY SHALL BE BINDING AS SOON AS THEY ARE PUBLISHED ON THE SITE IN THIS SECTION. THEREFORE, YOU ARE REQUESTED TO REGULARLY ACCESS THIS SECTION IN ORDER TO CHECK THE PUBLICATION OF THE MOST RECENT AND UPDATED PRIVACY POLICY.

                        @else
                            Договір публічної оферти<br><br>

                            Загальні положення<br><br>

                            1.1. Ця оферта є офіційною пропозицією компанії "lostkidsclub2000.com", надалі іменованої "Продавець", укласти Договір про дистанційну купівлю-продаж, а саме через Інтернет-магазин, надалі іменований "Договір", і розміщує Публічну оферту (пропозицію) на офіційному веб-сайті Продавця "lostkidsclub2000.com" (далі - "Сайт").<br><br>

                            1.2. Моментом повного та безумовного прийняття Покупцем пропозиції Продавця (акцепту) про укладення електронного договору купівлі-продажу товарів вважається факт оплати Покупцем замовлення на умовах цього Договору, протягом термінів та за цінами, зазначеними на Сайті Продавця.<br><br>

                            Терміни та визначення<br><br>

                            2.1. У цій оферті, якщо контекст не вимагає іншого, наступні терміни мають таке значення:<br><br>

                            "товари" - моделі, аксесуари, компоненти та супутні предмети;<br><br>

                            "Інтернет-магазин" - відповідно до Закону України "Про електронну комерцію", засіб для представлення або реалізації продукту, роботи або послуги шляхом здійснення електронної транзакції.<br><br>

                            "Продавець" - компанія, яка продає товари, представлені на Сайті.<br><br>

                            "Покупець" - фізична особа, яка уклала Договір з Продавцем на умовах, зазначених нижче.<br><br>

                            "Замовлення" - вибір окремих товарів зі списку товарів, зазначених Покупцем при оформленні замовлення та здійсненні оплати.<br><br>

                            Предмет Договору<br><br>

                            3.1. Продавець зобов'язується передати Товари у власність Покупцеві, а Покупець зобов'язується оплатити та прийняти Товари на умовах цього Договору.<br><br>

                            Цей Договір регулює купівлю-продаж товарів в Інтернет-магазині, зокрема:<br><br>

                            добровільний вибір Покупцем товарів в Інтернет-магазині;<br><br>

                            самостійне оформлення замовлення Покупцем в Інтернет-магазині;<br><br>

                            оплата Покупцем замовлення, оформленого в Інтернет-магазині;<br><br>

                            обробка та доставка замовлення у власність Покупцеві на умовах цього Договору.<br><br>

                            Процедура оформлення замовлення<br><br>

                            4.1. Покупець має право оформити замовлення на будь-які товари, представлені на Сайті Інтернет-магазину і доступні в наявності.<br><br>

                            4.2. Кожен товар може бути представлений в замовленні в будь-якій кількості.<br><br>

                            4.3. У разі відсутності товарів в наявності, Менеджер компанії зобов'язаний повідомити Покупця (по телефону або електронною поштою).<br><br>

                            4.4. У разі відсутності товару Покупець має право замінити його на товар подібної моделі, відмовитися від цього товару або скасувати замовлення.<br><br>

                            4.5. Купуючи товари, Покупець погоджується, що товар виготовляється на замовлення і не підлягає поверненню або обміну (тільки у випадку товарів неналежної якості).<br><br>

                            Процедура оплати замовлення<br><br>

                            5.1. Оплата проводиться на веб-сайті в повному обсязі вартості товарів, після чого товари будуть відправлені Покупцеві.<br><br>

                            5.2. У разі ненадходження коштів, Інтернет-магазин залишає за собою право скасувати замовлення.<br><br>

                            Умови доставки замовлення<br><br>

                            6.1. Доставка товарів, куплених в Інтернет-магазині, здійснюється до складів транспортних компаній, де видаються замовлення.<br><br>

                            6.2. Разом з замовленням Покупцеві надаються документи відповідно до законодавства України.<br><br>

                            Права та обов'язки сторін<br><br>

                            7.1. Продавець має право:<br><br>

                            в односторонньому порядку припинити надання послуг за цим Договором у разі порушення Покупцем умов цього Договору.<br>
                            7.2. Покупець зобов'язаний:<br><br>

                            своєчасно оплачувати та приймати замовлення на умовах цього Договору.<br>
                            7.3. Покупець має право:<br><br>

                            оформити замовлення в Інтернет-магазині;<br><br>

                            укласти електронний договір;<br><br>

                            вимагати від Продавця виконання умов цього Договору.<br><br>

                            Відповідальність сторін<br><br>

                            8.1. Сторони несуть відповідальність за невиконання або неналежне виконання умов цього Договору відповідно до цього Договору та чинного законодавства України.<br><br>

                            8.2. Продавець не несе відповідальності за:<br><br>

                            зміни, внесені виробником в зовнішній вигляд Товарів;<br><br>


                            - за незначні відхилення в колірній гамі товарів, які можуть відрізнятися від оригінального продукту лише через різну кольоропередачу моніторів персональних комп'ютерів різних моделей;<br>
                            - за зміст і точність інформації, наданої Покупцем при оформленні замовлення;<br>
                            - за затримки та перебої у наданні послуг (обробка замовлень і доставка товарів), які виникають з причин, що не залежать від Продавця;<br>
                            - за незаконні дії, вчинені Покупцем із використанням доступу до Інтернет-мережі;<br><br>

                            8.3. Покупець, використовуючи наданий йому доступ до Інтернет-мережі, самостійно несе відповідальність за шкоду, завдану його діями (особисто, навіть якщо інша особа використовувала його логін) фізичним або юридичним особам, державі чи моральним принципам.<br><br>

                            8.4. У разі настання форс-мажорних обставин сторони звільняються від виконання умов цього договору. Форс-мажорними обставинами для цього договору є події надзвичайного, непередбаченого характеру, які виключають або об'єктивно ускладнюють виконання цього договору, які сторони не могли передбачити і запобігти розумними засобами.<br><br>

                            8.5. Сторони докладають усіх зусиль для вирішення будь-яких суперечок виключно шляхом переговорів.<br><br>

                            Інші умови<br><br>

                            9.1. Інтернет-магазин залишає за собою право односторонньо змінювати цей договір, за умови, що зміни будуть опубліковані завчасно на сайті lostkidsclub2000.com.<br><br>

                            9.2. Інтернет-магазин створений для організації дистанційного продажу товарів через Інтернет.<br><br>

                            9.3. Покупець несе відповідальність за точність наданої інформації при оформленні замовлення. Водночас, приймаючи (оформлюючи замовлення і наступну оплату товарів), Покупець надає Продавцеві безумовну згоду на збір, обробку, зберігання та використання своїх персональних даних у розумінні Закону України "Про захист персональних даних."<br><br>

                            9.4. Оплата Покупцем замовлення, оформленого в Інтернет-магазині, означає повну згоду Покупця з умовами договору купівлі-продажу (публічної оферти).<br><br>

                            9.5. Дата укладення електронного договору між сторонами є дата акцепту умов відповідно до статті 11 Закону України "Про електронну комерцію."<br><br>

                            9.6. Використання ресурсів Інтернет-магазину для перегляду товарів, а також для оформлення замовлення Покупцем, є безкоштовним.<br><br>

                            9.7. Інформація, надана Покупцем, є конфіденційною. Інтернет-магазин використовує інформацію про Покупця виключно для обробки замовлення, надсилання повідомлень Покупцеві, доставки товарів, проведення розрахунків тощо.<br><br>

                            Процедура повернення товарів належної якості<br><br>

                            10.1. Повернення товарів до Інтернет-магазину здійснюється відповідно до чинного законодавства України.<br><br>

                            10.2. Повернення можливе лише для товарів неналежної якості.<br><br>

                            10.3. При поверненні товарів належної якості Інтернет-магазин повертає суму, сплачену за товар, за вирахуванням витрат Інтернет-магазину, пов’язаних із доставкою товару Покупцеві.<br><br>

                            Термін дії Договору<br><br>

                            11.1. Електронний договір вважається укладеним з моменту, коли особа, яка надіслала пропозицію укласти такий договір, отримує відповідь про акцепт цієї пропозиції в порядку, зазначеному в частині шостій статті 11 Закону України "Про електронну комерцію."<br><br>

                            11.2. До закінчення терміну цей Договір може бути припинений за взаємною згодою сторін до фактичної доставки товару з поверненням коштів.<br><br>

                            11.3. Сторони мають право односторонньо припинити цей договір у разі невиконання умов цього Договору однією зі сторін і в інших випадках, передбачених чинним законодавством України.<br><br>
                        @endif


                    </div>
                </div>
            </div>
        </section>
    </main>
@endsection
